parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  es6: true
  browser: true
extends: 'airbnb-base'
rules:
  import/extensions:
    - 2
    - js: 'always'
overrides:
  files: 'postcss.config.js'
  env:
    node: true
  rules:
    import/no-extraneous-dependencies:
      - devDependencies: true
